apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-annotations
spec:
  params:
    annotations:
      config.kubernetes.io/local-config: "true"
  source: |
    resource = option("resource_list")
    params = resource.functionConfig.spec.params
    # Use `k = v` to override existing annotations
    annotations = {k = v for k, v in params.annotations}
    items = [item | {
        metadata.annotations: annotations
    } for item in resource.items]
