apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
functionConfig:
  apiVersion: krm.kcl.dev/v1alpha1
  kind: KCLRun
  spec:
    params:
      name: app
      containers:
        nginx:
          image: nginx
          ports:
          - containerPort: 80
      service:
        ports:
        - port: 80
      labels:
        name: app
    source: oci://ghcr.io/kcl-lang/web-service
