apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-labels
spec:
  params:
    labels:
      config.kubernetes.io/local-config: "true"
  source: |
    resource = option("resource_list")
    params = option("params")
    # Use `k = v` to override existing labels
    labels = {k = v for k, v in params.labels}
    items = [item | {
        metadata.labels: labels
    } for item in resource.items]
